services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver_container
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - ./backups:/usr/local/backups
      - ./logs:/usr/local/logs
    tty: true
    